#############################################################################
# Makefile for building: FeatherGUI
# Generated by qmake (2.01a) (Qt 4.7.3) on: ?? 8? 8 16:25:49 2011
# Project:  GUI.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile GUI.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -Iinclude -IFeather/include -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/lib64/qt4
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 ./Feather/libFeather.a -lssl -lQtXml -L/usr/lib64 -L/usr/lib64/qt4 -lQtGui -L/usr/X11R6/lib -lQtNetwork -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Message/MsgDestination.cpp \
		Message/Msg.cpp \
		Message/InstantSMS.cpp \
		Message/ScheduledSMS.cpp \
		Account/FeatherAccount.cpp \
		Account/AccountManager.cpp \
		Forms/DialogCertification.cpp \
		Message/MsgManager.cpp \
		Message/AbstractMsgList.cpp \
		Message/MsgItem.cpp \
		Message/InstantSMSList.cpp \
		Message/ScheduledSMSList.cpp \
		Account/AccountList_TagItem_AccountItem.cpp \
		Account/AccountList_TagItem.cpp \
		Account/AccountList_TagItem_AccountItem_GroupItem.cpp \
		Account/AccountList.cpp \
		Forms/MainWindow.cpp \
		main.cpp \
		Account/AccountStatisticsList.cpp \
		Account/AccountStatisticsList_TagItem.cpp \
		Account/AccountStatisticsList_TagItem_AccountItem.cpp moc_Msg.cpp \
		moc_MsgManager.cpp \
		moc_FeatherAccount.cpp \
		moc_AccountManager.cpp \
		moc_DialogCertification.cpp \
		moc_MsgList.cpp \
		moc_AccountList.cpp \
		moc_MainWindow.cpp \
		moc_AccountStatisticsList.cpp
OBJECTS       = MsgDestination.o \
		Msg.o \
		InstantSMS.o \
		ScheduledSMS.o \
		FeatherAccount.o \
		AccountManager.o \
		DialogCertification.o \
		MsgManager.o \
		AbstractMsgList.o \
		MsgItem.o \
		InstantSMSList.o \
		ScheduledSMSList.o \
		AccountList_TagItem_AccountItem.o \
		AccountList_TagItem.o \
		AccountList_TagItem_AccountItem_GroupItem.o \
		AccountList.o \
		MainWindow.o \
		main.o \
		AccountStatisticsList.o \
		AccountStatisticsList_TagItem.o \
		AccountStatisticsList_TagItem_AccountItem.o \
		moc_Msg.o \
		moc_MsgManager.o \
		moc_FeatherAccount.o \
		moc_AccountManager.o \
		moc_DialogCertification.o \
		moc_MsgList.o \
		moc_AccountList.o \
		moc_MainWindow.o \
		moc_AccountStatisticsList.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		GUI.pro
QMAKE_TARGET  = FeatherGUI
DESTDIR       = 
TARGET        = FeatherGUI

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_MainWindow.h ui_DialogCertification.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GUI.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtXml.prl \
		/usr/lib64/qt4/libQtCore.prl \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtNetwork.prl
	$(QMAKE) -o Makefile GUI.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtXml.prl:
/usr/lib64/qt4/libQtCore.prl:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile GUI.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/FeatherGUI1.0.0 || $(MKDIR) .tmp/FeatherGUI1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/FeatherGUI1.0.0/ && $(COPY_FILE) --parents Message/Msg.h Message/MsgManager.h Account/FeatherAccount.h Account/AccountManager.h Forms/DialogCertification.h Message/MsgList.h Account/AccountList.h Forms/MainWindow.h Account/AccountStatisticsList.h .tmp/FeatherGUI1.0.0/ && $(COPY_FILE) --parents Message/MsgDestination.cpp Message/Msg.cpp Message/InstantSMS.cpp Message/ScheduledSMS.cpp Account/FeatherAccount.cpp Account/AccountManager.cpp Forms/DialogCertification.cpp Message/MsgManager.cpp Message/AbstractMsgList.cpp Message/MsgItem.cpp Message/InstantSMSList.cpp Message/ScheduledSMSList.cpp Account/AccountList_TagItem_AccountItem.cpp Account/AccountList_TagItem.cpp Account/AccountList_TagItem_AccountItem_GroupItem.cpp Account/AccountList.cpp Forms/MainWindow.cpp main.cpp Account/AccountStatisticsList.cpp Account/AccountStatisticsList_TagItem.cpp Account/AccountStatisticsList_TagItem_AccountItem.cpp .tmp/FeatherGUI1.0.0/ && $(COPY_FILE) --parents Forms/MainWindow.ui Forms/DialogCertification.ui .tmp/FeatherGUI1.0.0/ && (cd `dirname .tmp/FeatherGUI1.0.0` && $(TAR) FeatherGUI1.0.0.tar FeatherGUI1.0.0 && $(COMPRESS) FeatherGUI1.0.0.tar) && $(MOVE) `dirname .tmp/FeatherGUI1.0.0`/FeatherGUI1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/FeatherGUI1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Msg.cpp moc_MsgManager.cpp moc_FeatherAccount.cpp moc_AccountManager.cpp moc_DialogCertification.cpp moc_MsgList.cpp moc_AccountList.cpp moc_MainWindow.cpp moc_AccountStatisticsList.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Msg.cpp moc_MsgManager.cpp moc_FeatherAccount.cpp moc_AccountManager.cpp moc_DialogCertification.cpp moc_MsgList.cpp moc_AccountList.cpp moc_MainWindow.cpp moc_AccountStatisticsList.cpp
moc_Msg.cpp: Message/Msg.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Message/Msg.h -o moc_Msg.cpp

moc_MsgManager.cpp: Message/MsgManager.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Message/MsgManager.h -o moc_MsgManager.cpp

moc_FeatherAccount.cpp: Account/FeatherAccount.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Account/FeatherAccount.h -o moc_FeatherAccount.cpp

moc_AccountManager.cpp: Account/AccountManager.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Account/AccountManager.h -o moc_AccountManager.cpp

moc_DialogCertification.cpp: ui_DialogCertification.h \
		Forms/DialogCertification.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Forms/DialogCertification.h -o moc_DialogCertification.cpp

moc_MsgList.cpp: Message/MsgList.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Message/MsgList.h -o moc_MsgList.cpp

moc_AccountList.cpp: Account/AccountList.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Account/AccountList.h -o moc_AccountList.cpp

moc_MainWindow.cpp: ui_MainWindow.h \
		Forms/MainWindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Forms/MainWindow.h -o moc_MainWindow.cpp

moc_AccountStatisticsList.cpp: Account/AccountStatisticsList.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Account/AccountStatisticsList.h -o moc_AccountStatisticsList.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_MainWindow.h ui_DialogCertification.h
compiler_uic_clean:
	-$(DEL_FILE) ui_MainWindow.h ui_DialogCertification.h
ui_MainWindow.h: Forms/MainWindow.ui
	/usr/bin/uic Forms/MainWindow.ui -o ui_MainWindow.h

ui_DialogCertification.h: Forms/DialogCertification.ui
	/usr/bin/uic Forms/DialogCertification.ui -o ui_DialogCertification.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

MsgDestination.o: Message/MsgDestination.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MsgDestination.o Message/MsgDestination.cpp

Msg.o: Message/Msg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Msg.o Message/Msg.cpp

InstantSMS.o: Message/InstantSMS.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InstantSMS.o Message/InstantSMS.cpp

ScheduledSMS.o: Message/ScheduledSMS.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScheduledSMS.o Message/ScheduledSMS.cpp

FeatherAccount.o: Account/FeatherAccount.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FeatherAccount.o Account/FeatherAccount.cpp

AccountManager.o: Account/AccountManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AccountManager.o Account/AccountManager.cpp

DialogCertification.o: Forms/DialogCertification.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DialogCertification.o Forms/DialogCertification.cpp

MsgManager.o: Message/MsgManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MsgManager.o Message/MsgManager.cpp

AbstractMsgList.o: Message/AbstractMsgList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AbstractMsgList.o Message/AbstractMsgList.cpp

MsgItem.o: Message/MsgItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MsgItem.o Message/MsgItem.cpp

InstantSMSList.o: Message/InstantSMSList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InstantSMSList.o Message/InstantSMSList.cpp

ScheduledSMSList.o: Message/ScheduledSMSList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScheduledSMSList.o Message/ScheduledSMSList.cpp

AccountList_TagItem_AccountItem.o: Account/AccountList_TagItem_AccountItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AccountList_TagItem_AccountItem.o Account/AccountList_TagItem_AccountItem.cpp

AccountList_TagItem.o: Account/AccountList_TagItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AccountList_TagItem.o Account/AccountList_TagItem.cpp

AccountList_TagItem_AccountItem_GroupItem.o: Account/AccountList_TagItem_AccountItem_GroupItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AccountList_TagItem_AccountItem_GroupItem.o Account/AccountList_TagItem_AccountItem_GroupItem.cpp

AccountList.o: Account/AccountList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AccountList.o Account/AccountList.cpp

MainWindow.o: Forms/MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o Forms/MainWindow.cpp

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

AccountStatisticsList.o: Account/AccountStatisticsList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AccountStatisticsList.o Account/AccountStatisticsList.cpp

AccountStatisticsList_TagItem.o: Account/AccountStatisticsList_TagItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AccountStatisticsList_TagItem.o Account/AccountStatisticsList_TagItem.cpp

AccountStatisticsList_TagItem_AccountItem.o: Account/AccountStatisticsList_TagItem_AccountItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AccountStatisticsList_TagItem_AccountItem.o Account/AccountStatisticsList_TagItem_AccountItem.cpp

moc_Msg.o: moc_Msg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Msg.o moc_Msg.cpp

moc_MsgManager.o: moc_MsgManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MsgManager.o moc_MsgManager.cpp

moc_FeatherAccount.o: moc_FeatherAccount.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FeatherAccount.o moc_FeatherAccount.cpp

moc_AccountManager.o: moc_AccountManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AccountManager.o moc_AccountManager.cpp

moc_DialogCertification.o: moc_DialogCertification.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DialogCertification.o moc_DialogCertification.cpp

moc_MsgList.o: moc_MsgList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MsgList.o moc_MsgList.cpp

moc_AccountList.o: moc_AccountList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AccountList.o moc_AccountList.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_AccountStatisticsList.o: moc_AccountStatisticsList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AccountStatisticsList.o moc_AccountStatisticsList.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

